# Generated by Django 6.0.6 on 2026-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_description_name_role_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_name',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
