# Generated by Django 6.0.6 on 2026-07-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_department_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='description',
            new_name='description_name',
        ),
    ]
