# Generated by Django 6.0.6 on 2026-07-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_task_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectphase',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
