# Generated by Django 6.0.6 on 2026-07-03 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_created_at_alter_idea_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='ideacomment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='ideavote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
