# Generated by Django 6.0.6 on 2026-07-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_id_alter_ideacomment_id_alter_ideavote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Peer Review', 'Peer Review'), ('Product Manager Review', 'Product Manager Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Implementation', 'Implementation'), ('Impact Evaluation', 'Impact Evaluation'), ('Archived', 'Archived')], default='Draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ideavote',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('Like', 'Like'), ('Dislike', 'Dislike')], max_length=20, null=True),
        ),
    ]
