# Generated by Django 6.0.6 on 2026-07-13 09:13

import Base.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MpesaTransactionCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Amount')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Transaction Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction Cost',
                'verbose_name_plural': 'M-Pesa Transaction Costs',
                'db_table': 'mpesa_transaction_costs',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLogBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('user_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('event_message', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('entity_type', models.CharField(blank=True, max_length=200, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=150, null=True)),
                ('entity_name', models.CharField(blank=True, max_length=150, null=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Transaction_Log_Base.eventtype')),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('read_at', models.DateField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
                ('TransactionLogBase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_Log_Base.transactionlogbase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
