# Generated by Django 6.0.6 on 2026-07-20 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='TransactionLogBase',
            new_name='transaction_log',
        ),
    ]
