# Generated by Django 6.0.6 on 2026-07-02 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_log_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlogbase',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactionlogbase',
            name='name',
        ),
    ]
