# Generated by Django 6.0.6 on 2026-07-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlogbase',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Transaction_Log_Base.eventtype'),
        ),
    ]
