# Generated by Django 6.0.6 on 2026-07-03 05:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0002_alter_transactionlogbase_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('transactionlogbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transaction_Log_Base.transactionlogbase')),
                ('read_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('Transaction_Log_Base.transactionlogbase',),
        ),
        migrations.AlterField(
            model_name='transactionlogbase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
