# Generated by Django 6.0.6 on 2026-07-13 05:43

import Base.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_state_id'),
        ('Transaction_Log_Base', '0002_alter_transactionlogbase_created_at_and_more'),
        ('users', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlogbase',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.CreateModel(
            name='MpesaTransactionCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maximum Amount')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Transaction Cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
            ],
            options={
                'verbose_name': 'M-Pesa Transaction Cost',
                'verbose_name_plural': 'M-Pesa Transaction Costs',
                'db_table': 'mpesa_transaction_costs',
                'ordering': ['min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('read_at', models.DateField(blank=True, null=True)),
                ('TransactionLogBase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_Log_Base.transactionlogbase')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
