# Generated by Django 6.0.6 on 2026-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0002_alter_transactionlogbase_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
