# Generated by Django 6.0.6 on 2026-07-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0002_rename_transactionlogbase_notifications_transaction_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlogbase',
            name='event_date',
        ),
    ]
