# Generated by Django 6.0.6 on 2026-07-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0003_alter_transactionlogbase_id_mpesatransactioncost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlogbase',
            name='entity_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlogbase',
            name='entity_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
