# Generated by Django 6.0.6 on 2026-07-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0003_remove_transactionlogbase_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlogbase',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
