# Generated by Django 6.0.6 on 2026-07-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_Log_Base', '0004_transactionlogbase_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionlogbase',
            name='event_date',
        ),
    ]
