# Generated by Django 6.0.6 on 2026-07-03 05:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_state_created_at_alter_state_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
