# Generated by Django 6.0.6 on 2026-07-06 08:03

import Base.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0003_alter_state_id'),
        ('users', '0005_rename_description_role_description_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('threshold', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('points', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_history', to='users.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('action', models.CharField(max_length=100, unique=True)),
                ('points', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date modified')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gamification.badge')),
                ('state', models.ForeignKey(default=Base.models.get_default_state, on_delete=django.db.models.deletion.CASCADE, to='Base.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
