# Generated by Django 6.0.6 on 2026-07-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
    ]
